### ISSUE TITLE
Status on ongoing goals gives misleading/discouraging stats

### ISSUE THREAD

**Issue by danbartlett** [danbartlett/opensit#200]
I think showing the 'You've achieved...' sentence below is un-necessary for ongoing goals, as an ongoing goal only takes into consideration your compliance over the last two weeks. Even so, this number feels wrong - I think the 14 is just the number of days of compliance in last 2 weeks, which again is misleading

![goals_ongoing](https://cloud.githubusercontent.com/assets/1884651/5757409/fe769ab0-9cb2-11e4-9673-37faf6e5ba93.png)

**Comment by johnthepink** [comment]
Would it be worth it to show something like "You've achieved your goal x out of the last 14 days" if the goal started more than 14 days ago? Or, just get rid of it entirely?

**Comment by danbartlett** [comment]
"You've achieved your goal x out of the last 14 days" - that sounds like a good solution to me.

**Comment by danbartlett** [comment]
Actually 14 will sound arbitrary to a user - I think just remove it.
